# docker-compose.yml
name: SEECADI
services:
  postgresql:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=dev
      - POSTGRES_HOST_AUTH_METHOD=trust
      - LANG=en_US.utf8
      - LC_COLLATE=en_US.utf8
      - LC_CTYPE=en_US.utf8
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
