--ANTECEDENTES
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_ANTECEDENTES"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_ANTECEDENTES"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."ANTECEDENTES" 
ALTER COLUMN ant_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_ANTECEDENTES"');

--colegios
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_COLEGIOS"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_COLEGIOS"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."COLEGIOS" 
ALTER COLUMN col_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_COLEGIOS"');


--DISCAPACIDADES
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_DISCAPACIDADES"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_DISCAPACIDADES"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."DISCAPACIDADES" 
ALTER COLUMN ant_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_DISCAPACIDADES"');


--EMPLEADOS
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_EMPLEADOS"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_EMPLEADOS"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."EMPLEADOS" 
ALTER COLUMN emp_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_EMPLEADOS"');


--ESTUDIANTE_DISCAPACIDAD
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_ESTUDIANTE_DISCAPACIDAD"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_ESTUDIANTE_DISCAPACIDAD"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."ESTUDIANTE_DISCAPACIDAD" 
ALTER COLUMN emp_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_ESTUDIANTE_DISCAPACIDAD"');


--ESTUDIANTE_EVAL_MODALIDAD
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_ESTUDIANTE_EVAL_MODALIDAD"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_ESTUDIANTE_EVAL_MODALIDAD"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."ESTUDIANTE_EVAL_MODALIDAD" 
ALTER COLUMN emp_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_ESTUDIANTE_EVAL_MODALIDAD"');



--ESTUDIANTES
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_ESTUDIANTES"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_ESTUDIANTES"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."ESTUDIANTES" 
ALTER COLUMN est_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_ESTUDIANTES"');


--EVALUACIONES
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_EVALUACIONES"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_EVALUACIONES"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."EVALUACIONES" 
ALTER COLUMN eva_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_EVALUACIONES"');

--MODALIDAD_ESTUDIOS
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_MODALIDAD_ESTUDIOS"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_MODALIDAD_ESTUDIOS"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."MODALIDAD_ESTUDIOS" 
ALTER COLUMN eva_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_MODALIDAD_ESTUDIOS"');


--PERMISOS
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_PERMISOS"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_PERMISOS"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."PERMISOS" 
ALTER COLUMN prm_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_PERMISOS"');

--PERMISO_RECURSOS
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_PERMISO_RECURSOS"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_PERMISO_RECURSOS"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."PERMISO_RECURSOS" 
ALTER COLUMN prr_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_PERMISO_RECURSOS"');

--PERSONAS
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_PERSONAS"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_PERSONAS"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."PERSONAS" 
ALTER COLUMN per_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_PERSONAS"');

--PROFESIONALES
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_PROFESIONES"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_PROFESIONES"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."PROFESIONES" 
ALTER COLUMN prf_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_PROFESIONES"');

--RECURSOS
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_RECURSOS"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_RECURSOS"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."RECURSOS" 
ALTER COLUMN rec_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_RECURSOS"');

--ROLES
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_ROLES"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_ROLES"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."ROLES" 
ALTER COLUMN rol_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_ROLES"');

--ROL_PERMISOS
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_ROL_PERMISOS"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_ROL_PERMISOS"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."ROL_PERMISOS" 
ALTER COLUMN rlp_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_ROL_PERMISOS"');

--TIPO_EVALUACIONES
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_TIPO_EVALUACIONES"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_TIPO_EVALUACIONES"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."TIPO_EVALUACIONES" 
ALTER COLUMN tev_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_TIPO_EVALUACIONES"');

--USUARIOS
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_USUARIOS"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_USUARIOS"
    OWNER TO dev;

ALTER TABLE   "SEECADI"."USUARIOS" 
ALTER COLUMN usr_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_USUARIOS"');

--USUARIO_ROLES
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_USUARIO_ROLES"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_USUARIO_ROLES"
    OWNER TO dev;


ALTER TABLE   "SEECADI"."USUARIO_ROLES" 
ALTER COLUMN urr_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_USUARIO_ROLES"');

--ANTECEDENTES
CREATE SEQUENCE IF NOT EXISTS "SEECADI"."SQ_ANTECEDENTES"
    INCREMENT 1
    START 10000
    MINVALUE 1
    CACHE 1;

ALTER SEQUENCE "SEECADI"."SQ_ANTECEDENTES"
    OWNER TO dev;


ALTER TABLE   "SEECADI"."ANTECEDENTES" 
ALTER COLUMN ant_uid_pk SET DEFAULT NEXTVAL('"SEECADI"."SQ_ANTECEDENTES"');





	