CREATE OR REPLACE FUNCTION "SEECADI".FN_UPD_TABLES() RETURNS TRIGGER
AS
$$

BEGIN
 
  NEW.fecha_modificacion := NOW();
 
  RETURN NEW;
END
$$
Language plpgsql;


-- ANTECEDENTES
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_ANTECEDENTES" BEFORE UPDATE ON "SEECADI"."ANTECEDENTES"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();
	
	
-- COLEGIOS
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_COLEGIOS" BEFORE UPDATE ON "SEECADI"."COLEGIOS"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();


-- DISCAPACIDADES
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_DISCAPACIDADES" BEFORE UPDATE ON "SEECADI"."DISCAPACIDADES"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();

-- EMPLEADOS
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_EMPLEADOS" BEFORE UPDATE ON "SEECADI"."EMPLEADOS"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();

-- ESTUDIANTE_DISCAPACIDAD
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_ESTUDIANTE_DISCAPACIDAD" BEFORE UPDATE ON "SEECADI"."ESTUDIANTE_DISCAPACIDAD"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();




-- ESTUDIANTES
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_ESTUDIANTES" BEFORE UPDATE ON "SEECADI"."ESTUDIANTES"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();
	
-- EVALUACIONES
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_EVALUACIONES" BEFORE UPDATE ON "SEECADI"."EVALUACIONES"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();


-- MODALIDAD_ESTUDIOS
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_MODALIDAD_ESTUDIOS" BEFORE UPDATE ON "SEECADI"."MODALIDAD_ESTUDIOS"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();


-- PERMISOS
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_PERMISOS" BEFORE UPDATE ON "SEECADI"."PERMISOS"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();
	
-- PERMISO_RECURSOS
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_PERMISO_RECURSOS" BEFORE UPDATE ON "SEECADI"."PERMISO_RECURSOS"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();
	
-- PERSONAS
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_PERSONAS" BEFORE UPDATE ON "SEECADI"."PERSONAS"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();
	
-- PROFESIONES
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_PROFESIONES" BEFORE UPDATE ON "SEECADI"."PROFESIONES"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();
	
-- RECURSOS
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_RECURSOS" BEFORE UPDATE ON "SEECADI"."RECURSOS"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();
	
-- ROLES
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_ROLES" BEFORE UPDATE ON "SEECADI"."ROLES"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();	
	
	
-- ROL_PERMISOS
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_ROL_PERMISOS" BEFORE UPDATE ON "SEECADI"."ROL_PERMISOS"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();		
	
	
-- TIPO_EVALUACIONES
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_TIPO_EVALUACIONES" BEFORE UPDATE ON "SEECADI"."TIPO_EVALUACIONES"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();		
	
-- USUARIOS
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_USUARIOS" BEFORE UPDATE ON "SEECADI"."USUARIOS"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();		

-- USUARIO_ROLES
CREATE OR REPLACE TRIGGER "SEECADI.TRG_UPD_USUARIO_ROLES" BEFORE UPDATE ON "SEECADI"."USUARIO_ROLES"
  FOR EACH ROW
    
	EXECUTE PROCEDURE "SEECADI".FN_UPD_TABLES();	